class CreateInfos < ActiveRecord::Migration
  def change
    create_table :infos do |t|
      t.string :Address1
      t.string :Address2
      t.boolean :AnyFlag
      t.string :AuthNo
      t.string :BillingAddress1
      t.string :BillingAddress2
      t.string :BillingCity
      t.string :BillingCompany
      t.string :BillingCountry
      t.string :BillingEmail
      t.string :BillingEmail2
      t.string :BillingFirstName
      t.string :BillingLastName
      t.string :BillingPhone
      t.string :BillingState
      t.string :BillingZipCode
      t.string :CardNumber
      t.decimal :CashRecvd
      t.string :CheckNumber
      t.string :City
      t.integer :Cnt2
      t.integer :Cnt1
      t.integer :Cnt3
      t.integer :Cnt4
      t.integer :Cnt5
      t.integer :Cnt6
      t.integer :Cnt8
      t.integer :Cnt9
      t.integer :Cnt10
      t.text :Comment
      t.string :Company
      t.string :Conference
      t.string :Country
      t.string :CustPONo
      t.string :CustType
      t.boolean :Deleted
      t.string :DidAffil
      t.string :DidCCRpt
      t.string :DidEmail
      t.string :DidPrint
      t.string :DidShort
      t.string :DidVisa
      t.integer :Done
      t.string :Email
      t.string :Email2
      t.string :ExpirDate
      t.string :FECustNum
      t.string :FirstName
      t.boolean :Flag1
      t.boolean :Flag2
      t.boolean :Flag8
      t.boolean :Flag9
      t.boolean :Flag10
      t.boolean :Flag10
      t.boolean :FreeUpgrade
      t.boolean :Gift
      t.boolean :GotEmail
      t.string :InvoiceNo
      t.decimal :InvTotal
      t.integer :Kind
      t.string :LastName
      t.boolean :NoEmailContact
      t.integer :NoEmailContact
      t.integer :OldRIN
      t.datetime :OrderDate
      t.boolean :OrderTag
      t.string :Origin
      t.decimal :OtherAmount
      t.string :OtherDesc
      t.integer :PackSlipCnt
      t.string :Phone
      t.integer :RegisterTo
      t.string :SalesPerson
      t.decimal :SalesTax
      t.decimal :SalesTaxAdj
      t.datetime :ShipDate
      t.decimal :ShippingChg
      t.string :ShipType
      t.string :ShipVia
      t.string :ShopOrderNum
      t.string :SiteLicNum
      t.string :State
      t.boolean :Tagged
      t.string :TaxExempt
      t.string :TempCustNum
      t.text :Terms
      t.decimal :TotalSale
      t.decimal :TotalSale
      t.string :xDidAffil
      t.string :xDidPrint
      t.string :xDidVisa
      t.string :xxRecNum
      t.string :ZipCode

      t.timestamps
    end
  end
end
